server:
  port: ${SERVISE_PORT}

spring:
  application:
    name: auth-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs