version: "3.9"
services:
    rabbitmq:
        hostname: rabbitmq
        image: rabbitmq:3.8.14-management
        container_name: 'rabbitmq'
        restart: always
        ports:
            - 5672:5672
            - 15672:15672
        volumes:
            - ~/.docker-conf/rabbitmq/data/:/var/lib/rabbitmq/mnesia/
        networks:
            - test-network

    postgres-auth-service:
        container_name: postgres-auth-service
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
        - 5432:5432
        networks:
        - test-network
        volumes: 
        - ~/.docker-conf/postgres/data/:/var/lib/postgresql/data

    postgres-advert-service:
        container_name: postgres-advert-service
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
            - 5433:5432
        networks:
            - test-network
        volumes:
            - ~/.docker-conf/postgres/data/:/var/lib/postgresql/data

    postgres-report-service:
        container_name: postgres-report-service
        image: postgres:14-alpine
        restart: always
        environment:
            POSTGRES_DB: postgres
            POSTGRES_USER: postgres
            POSTGRES_PASSWORD: root
        ports:
        - 5434:5432
        networks:
        - test-network
        volumes: 
        - ~/.docker-conf/postgres/data/:/var/lib/postgresql/data

networks:
    test-network:
        driver: bridge  
