server:
  port: 8082
spring:
  application:
    name: advert-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5433/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: localhost
    port: 5672
    username: guest
    password: guest
sr:
  rabbit:
    queue:
      name: advert-queue
    routing:
      name: advert-routing
    exchange:
      name: advert-exchange
