server:
  port: ${SERVISE_PORT}

spring:
  application:
    name: report-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: ${POSTGRES_CONNECTION_URL}
    username: ${POSTGRES_USERNAME}
    password: ${POSTGRES_PASSWORD}
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
  rabbitmq:
    host: ${RABBITMQ_HOST}
    port: ${RABBITMQ_PORT}
    username: ${RABBITMQ_USERNAME}
    password: ${RABBITMQ_PASSWORD}

sr:
  rabbit:
    queue:
      name: ${QUEUE_NAME}
    routing:
      name:  ${ROUTING_NAME}
    exchange:
      name: ${EXCHANGE_NAME}

api-call:
  uri:  ${API_CALL_URI}

springfox:
  documentation:
    swagger:
      v2:
        path: /api-docs