server:
  port: 8083
spring:
  application:
    name: report-service
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5434/postgres
    username: postgres
    password: root
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
    database-platform: org.hibernate.dialect.PostgreSQLDialect
sr:
  rabbit:
    queue:
      name: advert-queue
    routing:
      name: advert-routing
    exchange:
      name: advert-exchange
api-call:
  uri: http://localhost:8081/api/v1/token/
