### Login user
POST http://localhost:8081/login
Content-Type: application/x-www-form-urlencoded

username=jdoe&password=1234

### Login admin
POST http://localhost:8081/login
Content-Type: application/x-www-form-urlencoded

username=admin&password=1234

### List Users  user
GET http://localhost:8081/api/users
Content-Type: application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZG9lIiwicm9sZXMiOlsiUk9MRV9VU0VSIl0sImlzcyI6Imh0dHA6Ly9sb2NhbGhvc3Q6ODA4MC9sb2dpbiIsImV4cCI6MTY1NzYzMDgzOX0.pgveIc7ojwHd5o0dKb-q175FliHgxSmNt2TFRcqncpU

### List Users  admin
GET http://localhost:8081/api/v1/users
Content-Type: application/json
Authorization: Bearer yJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJzdWIiOiJqZG9lMiIsInJvbGVzIjpbIlJPTEVfQURNSU4iXSwiaXNzIjoiaHR0cDovL2xvY2FsaG9zdDo4MDgxL2xvZ2luIiwiZXhwIjoxNjU4MDgxOTQyfQ.HMmsK-ktyp3bMJ2Yk78ihjtt_fPYZJrvC1th25XbKok

### Register
GET http://localhost:8081/api/v1/register
Content-Type: application/json